### ISSUE TITLE
Perhaps reduce the spacing above `Welcome to optiMize` to keep things consistent

### ISSUE THREAD

**Issue by vinayh** [optimizemi/frontend#5]
There seems to be more space above the `Welcome to optiMize` title compared to the space below the `I'm Interested` button and around the `Stay in touch` section, if that makes sense.

Screenshot: http://i.imgur.com/MNAu9uW.png

**Comment by john-dickinson** [comment]
Can I ask what screen resolution this is? or better yet how many pixels wide the window is in this screenshot?

**Comment by vinayh** [comment]
1920x1080 (so 1920 wide). Playing around with Firefox's response design tool I can't really find a nice pattern of resolutions that causes this issue. It does also seem to exist in 1024x768 apparently.
http://i.imgur.com/Ai3pppj.png

**Comment by john-dickinson** [comment]
okay, thanks!

**Comment by vinayh** [comment]
@john-dickinson Here's a video of me playing with widths. It seems to jump around at specific resolutions.

https://vid.me/kflG
