### ISSUE TITLE
Newsletter form could do with some feedback

### ISSUE THREAD

**Issue by vinayh** [optimizemi/frontend#6]
Right now it's not clear whether the request went through without checking in the network pane of Inspect Element or something, so a user probably has no idea if their name/email was logged. Perhaps just an `Info Received` blurb if the request succeeds would fix this. Should be able to do this in the JQuery.

**Comment by vinayh** [comment]
I just added better response formatting for the request on the backend side, and will add basic `console.log` status reporting now.

**Comment by john-dickinson** [comment]
Will work on this, was waiting until we got a working form hah

**Comment by vinayh** [comment]
Haha yep, just added better handling of the API response (JQuery handles this sort of awkwardly where in the case of a success `response.status` is the `status` in the response body, but in the case of a fail `response.status` is the status code..)

In any case that should help you so you can make those display things to the user instead.

**Comment by john-dickinson** [comment]
This is fixed
